# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dht.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dht.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdht.proto\x12\x06\x64ht.pb\"\x7f\n\x06Record\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\x0c\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12\x14\n\x0ctimeReceived\x18\x05 \x01(\t\x12\x12\n\tpublisher\x18\x9a\x05 \x01(\x0c\x12\x0c\n\x03ttl\x18\x89\x06 \x01(\r\"\xed\x03\n\x07Message\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.dht.pb.Message.MessageType\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\x1e\n\x06record\x18\x03 \x01(\x0b\x32\x0e.dht.pb.Record\x12)\n\x0b\x63loserPeers\x18\x08 \x03(\x0b\x32\x14.dht.pb.Message.Peer\x12+\n\rproviderPeers\x18\t \x03(\x0b\x32\x14.dht.pb.Message.Peer\x12\x17\n\x0f\x63lusterLevelRaw\x18\n \x01(\x05\x1aU\n\x04Peer\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\r\n\x05\x61\x64\x64rs\x18\x02 \x03(\x0c\x12\x32\n\nconnection\x18\x03 \x01(\x0e\x32\x1e.dht.pb.Message.ConnectionType\"i\n\x0bMessageType\x12\r\n\tPUT_VALUE\x10\x00\x12\r\n\tGET_VALUE\x10\x01\x12\x10\n\x0c\x41\x44\x44_PROVIDER\x10\x02\x12\x11\n\rGET_PROVIDERS\x10\x03\x12\r\n\tFIND_NODE\x10\x04\x12\x08\n\x04PING\x10\x05\"W\n\x0e\x43onnectionType\x12\x11\n\rNOT_CONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01\x12\x0f\n\x0b\x43\x41N_CONNECT\x10\x02\x12\x12\n\x0e\x43\x41NNOT_CONNECT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dht_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECORD']._serialized_start=21
  _globals['_RECORD']._serialized_end=148
  _globals['_MESSAGE']._serialized_start=151
  _globals['_MESSAGE']._serialized_end=644
  _globals['_MESSAGE_PEER']._serialized_start=363
  _globals['_MESSAGE_PEER']._serialized_end=448
  _globals['_MESSAGE_MESSAGETYPE']._serialized_start=450
  _globals['_MESSAGE_MESSAGETYPE']._serialized_end=555
  _globals['_MESSAGE_CONNECTIONTYPE']._serialized_start=557
  _globals['_MESSAGE_CONNECTIONTYPE']._serialized_end=644
# @@protoc_insertion_point(module_scope)
