# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identify.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'identify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentify.proto\x12\x08identify\"\x8a\x01\n\x08Identify\x12\x11\n\tpublicKey\x18\x01 \x01(\x0c\x12\x13\n\x0blistenAddrs\x18\x02 \x03(\x0c\x12\x11\n\tprotocols\x18\x03 \x03(\t\x12\x14\n\x0cobservedAddr\x18\x04 \x01(\x0c\x12\x17\n\x0fprotocolVersion\x18\x05 \x01(\t\x12\x14\n\x0c\x61gentVersion\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDENTIFY']._serialized_start=29
  _globals['_IDENTIFY']._serialized_end=167
# @@protoc_insertion_point(module_scope)
